// Package store is the Postgres-backed persistence layer: schema migrations,
// help_requests status transitions, submission snapshots, and the
// append-only events/llm_calls logs.
package store

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/profoundmentalretardation/problem-helper/migrations"
)

// Status is a help_requests.status value.
type Status string

const (
	StatusPending       Status = "pending"
	StatusRunning       Status = "running"
	StatusAlreadySolved Status = "already_solved"
	StatusNoSubmissions Status = "no_submissions"
	StatusDone          Status = "done"
	StatusNoFix         Status = "no_fix"
	StatusNoHint        Status = "no_hint"
	StatusFailed        Status = "failed"
)

// legalTransitions is the status graph from the plan's Technical Details:
// pending -> running -> {terminal...}; running -> pending is the crash
// reclaim path. Any status absent as a key is terminal.
var legalTransitions = map[Status][]Status{
	StatusPending: {StatusRunning},
	StatusRunning: {
		StatusAlreadySolved,
		StatusNoSubmissions,
		StatusDone,
		StatusNoFix,
		StatusNoHint,
		StatusFailed,
		StatusPending,
	},
}

// ErrDuplicateRequest is returned when a help_requests row with the same id
// already exists.
var ErrDuplicateRequest = errors.New("store: help request already exists")

// ErrUnknownRequest is returned when an operation references a request_id
// that has no help_requests row.
var ErrUnknownRequest = errors.New("store: unknown request")

// ErrIllegalTransition is returned when a status transition is not allowed
// by the graph in the plan's Technical Details.
type ErrIllegalTransition struct {
	From, To Status
}

func (e *ErrIllegalTransition) Error() string {
	return fmt.Sprintf("store: illegal status transition from %q to %q", e.From, e.To)
}

// dbtx is satisfied by *pgxpool.Pool, *pgxpool.Conn and pgx.Tx, so Store can
// run either against the pool directly or against a single transaction
// (see store_test.go for the test-isolation rationale).
type dbtx interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

// Store is the persistence layer, bound to either a pool or a transaction.
type Store struct {
	db dbtx
}

// New wraps a connected pool.
func New(pool *pgxpool.Pool) *Store {
	return &Store{db: pool}
}

// WithTx returns a Store bound to tx instead of the original pool/conn —
// used by tests to isolate each test in a rolled-back transaction.
func WithTx(tx pgx.Tx) *Store {
	return &Store{db: tx}
}

// Migrate applies every migrations/*.sql file, in filename order, that has
// not already been recorded in schema_migrations. Safe to call repeatedly.
func Migrate(ctx context.Context, pool *pgxpool.Pool) error {
	if _, err := pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS schema_migrations (
			name        TEXT PRIMARY KEY,
			applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
		)`); err != nil {
		return fmt.Errorf("store: creating schema_migrations: %w", err)
	}

	entries, err := migrations.FS.ReadDir(".")
	if err != nil {
		return fmt.Errorf("store: reading migrations dir: %w", err)
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".sql") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)

	for _, name := range names {
		var applied bool
		if err := pool.QueryRow(ctx,
			`SELECT EXISTS (SELECT 1 FROM schema_migrations WHERE name = $1)`, name,
		).Scan(&applied); err != nil {
			return fmt.Errorf("store: checking migration %s: %w", name, err)
		}
		if applied {
			continue
		}

		sqlBytes, err := migrations.FS.ReadFile(name)
		if err != nil {
			return fmt.Errorf("store: reading migration %s: %w", name, err)
		}

		tx, err := pool.Begin(ctx)
		if err != nil {
			return fmt.Errorf("store: beginning migration tx for %s: %w", name, err)
		}
		if _, err := tx.Exec(ctx, string(sqlBytes)); err != nil {
			_ = tx.Rollback(ctx)
			return fmt.Errorf("store: applying migration %s: %w", name, err)
		}
		if _, err := tx.Exec(ctx,
			`INSERT INTO schema_migrations (name) VALUES ($1)`, name,
		); err != nil {
			_ = tx.Rollback(ctx)
			return fmt.Errorf("store: recording migration %s: %w", name, err)
		}
		if err := tx.Commit(ctx); err != nil {
			return fmt.Errorf("store: committing migration %s: %w", name, err)
		}
	}
	return nil
}

// HelpRequestInput creates a help_requests row; the caller supplies ID
// (generated by the API layer) since request_id is returned synchronously
// from POST /help before the worker ever runs.
type HelpRequestInput struct {
	ID                uuid.UUID
	UserID            string
	ProblemID         string
	Platform          string
	NSubmissionsTaken int
}

// HelpRequest is a help_requests row.
type HelpRequest struct {
	ID                uuid.UUID
	UserID            string
	ProblemID         string
	Platform          string
	NSubmissionsTaken int
	Status            Status
	FailureReason     *string
	BestSubmissionID  *uuid.UUID
	HintID            *uuid.UUID
	Useless           bool
	Error             *string
	ClaimedBy         *string
	HeartbeatAt       *time.Time
	ResumeStep        *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// CreateHelpRequest inserts a new help_requests row with status=pending.
func (s *Store) CreateHelpRequest(ctx context.Context, in HelpRequestInput) error {
	_, err := s.db.Exec(ctx, `
		INSERT INTO help_requests (id, user_id, problem_id, platform, n_submissions_taken, status)
		VALUES ($1, $2, $3, $4, $5, $6)`,
		in.ID, in.UserID, in.ProblemID, in.Platform, in.NSubmissionsTaken, StatusPending,
	)
	if err != nil {
		if isUniqueViolation(err) {
			return fmt.Errorf("%w: id %s", ErrDuplicateRequest, in.ID)
		}
		return fmt.Errorf("store: creating help request: %w", err)
	}
	return nil
}

// GetHelpRequest fetches a help_requests row by id.
func (s *Store) GetHelpRequest(ctx context.Context, id uuid.UUID) (*HelpRequest, error) {
	row := s.db.QueryRow(ctx, `
		SELECT id, user_id, problem_id, platform, n_submissions_taken, status,
		       failure_reason, best_submission_id, hint_id, useless, error,
		       claimed_by, heartbeat_at, resume_step, created_at, updated_at
		FROM help_requests WHERE id = $1`, id)

	var hr HelpRequest
	var status string
	if err := row.Scan(
		&hr.ID, &hr.UserID, &hr.ProblemID, &hr.Platform, &hr.NSubmissionsTaken, &status,
		&hr.FailureReason, &hr.BestSubmissionID, &hr.HintID, &hr.Useless, &hr.Error,
		&hr.ClaimedBy, &hr.HeartbeatAt, &hr.ResumeStep, &hr.CreatedAt, &hr.UpdatedAt,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("%w: id %s", ErrUnknownRequest, id)
		}
		return nil, fmt.Errorf("store: getting help request: %w", err)
	}
	hr.Status = Status(status)
	return &hr, nil
}

// TransitionStatus moves a help_requests row to a new status, validating the
// transition against the graph in the plan's Technical Details. Illegal
// transitions (including any transition out of a terminal status) return
// *ErrIllegalTransition and do not modify the row.
func (s *Store) TransitionStatus(ctx context.Context, id uuid.UUID, to Status) error {
	row := s.db.QueryRow(ctx, `SELECT status FROM help_requests WHERE id = $1 FOR UPDATE`, id)
	var current string
	if err := row.Scan(&current); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return fmt.Errorf("%w: id %s", ErrUnknownRequest, id)
		}
		return fmt.Errorf("store: reading status for transition: %w", err)
	}
	from := Status(current)

	if !isLegalTransition(from, to) {
		return &ErrIllegalTransition{From: from, To: to}
	}

	if _, err := s.db.Exec(ctx,
		`UPDATE help_requests SET status = $1, updated_at = now() WHERE id = $2`, to, id,
	); err != nil {
		return fmt.Errorf("store: updating status: %w", err)
	}
	return nil
}

func isLegalTransition(from, to Status) bool {
	for _, allowed := range legalTransitions[from] {
		if allowed == to {
			return true
		}
	}
	return false
}

// ClaimNext atomically claims one pending help_requests row for workerID,
// using SELECT ... FOR UPDATE SKIP LOCKED so concurrent claimants each land
// on a distinct row instead of blocking on one another. Returns nil, nil if
// no row is pending — a miss, not an error.
func (s *Store) ClaimNext(ctx context.Context, workerID string) (*HelpRequest, error) {
	row := s.db.QueryRow(ctx, `
		UPDATE help_requests
		SET status = $1, claimed_by = $2, heartbeat_at = now(), updated_at = now()
		WHERE id = (
			SELECT id FROM help_requests
			WHERE status = $3
			ORDER BY created_at
			FOR UPDATE SKIP LOCKED
			LIMIT 1
		)
		RETURNING id, user_id, problem_id, platform, n_submissions_taken, status,
		          failure_reason, best_submission_id, hint_id, useless, error,
		          claimed_by, heartbeat_at, resume_step, created_at, updated_at`,
		StatusRunning, workerID, StatusPending)

	var hr HelpRequest
	var status string
	if err := row.Scan(
		&hr.ID, &hr.UserID, &hr.ProblemID, &hr.Platform, &hr.NSubmissionsTaken, &status,
		&hr.FailureReason, &hr.BestSubmissionID, &hr.HintID, &hr.Useless, &hr.Error,
		&hr.ClaimedBy, &hr.HeartbeatAt, &hr.ResumeStep, &hr.CreatedAt, &hr.UpdatedAt,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("store: claiming next help request: %w", err)
	}
	hr.Status = Status(status)
	return &hr, nil
}

// Heartbeat refreshes heartbeat_at for a request its claimant is still
// actively working. A no-op (not an error) if the row is no longer running
// — e.g. it finished between the last tick and this one.
func (s *Store) Heartbeat(ctx context.Context, id uuid.UUID) error {
	if _, err := s.db.Exec(ctx,
		`UPDATE help_requests SET heartbeat_at = now() WHERE id = $1 AND status = $2`,
		id, StatusRunning,
	); err != nil {
		return fmt.Errorf("store: updating heartbeat: %w", err)
	}
	return nil
}

// ReclaimStale moves running rows whose heartbeat is older than before back
// to pending, clearing claimed_by/heartbeat_at so another worker can claim
// them. resume_step is deliberately left untouched, so the row resumes at
// its last completed pipeline step instead of restarting. Returns the
// reclaimed request ids.
func (s *Store) ReclaimStale(ctx context.Context, before time.Time) ([]uuid.UUID, error) {
	rows, err := s.db.Query(ctx, `
		UPDATE help_requests
		SET status = $1, claimed_by = NULL, heartbeat_at = NULL, updated_at = now()
		WHERE status = $2 AND heartbeat_at < $3
		RETURNING id`,
		StatusPending, StatusRunning, before,
	)
	if err != nil {
		return nil, fmt.Errorf("store: reclaiming stale requests: %w", err)
	}
	defer rows.Close()

	var ids []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, fmt.Errorf("store: scanning reclaimed request id: %w", err)
		}
		ids = append(ids, id)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterating reclaimed requests: %w", err)
	}
	return ids, nil
}

// SetResumeStep records the last pipeline step a request completed, so a
// crash-reclaimed row resumes there instead of restarting from step 1.
func (s *Store) SetResumeStep(ctx context.Context, id uuid.UUID, step string) error {
	tag, err := s.db.Exec(ctx,
		`UPDATE help_requests SET resume_step = $1, updated_at = now() WHERE id = $2`, step, id)
	if err != nil {
		return fmt.Errorf("store: setting resume step: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("%w: id %s", ErrUnknownRequest, id)
	}
	return nil
}

// SetBestSubmission records which snapshotted submission the pipeline picked
// as best for this request.
func (s *Store) SetBestSubmission(ctx context.Context, id, submissionID uuid.UUID) error {
	tag, err := s.db.Exec(ctx,
		`UPDATE help_requests SET best_submission_id = $1, updated_at = now() WHERE id = $2`, submissionID, id)
	if err != nil {
		return fmt.Errorf("store: setting best submission: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("%w: id %s", ErrUnknownRequest, id)
	}
	return nil
}

// SetHintID records which hints row was (or will be) delivered for this
// request.
func (s *Store) SetHintID(ctx context.Context, id, hintID uuid.UUID) error {
	tag, err := s.db.Exec(ctx,
		`UPDATE help_requests SET hint_id = $1, updated_at = now() WHERE id = $2`, hintID, id)
	if err != nil {
		return fmt.Errorf("store: setting hint id: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("%w: id %s", ErrUnknownRequest, id)
	}
	return nil
}

// SetFailureReason records why a no_fix/no_hint request stopped short of
// delivering a hint (e.g. "max_retries", "cost_cap").
func (s *Store) SetFailureReason(ctx context.Context, id uuid.UUID, reason string) error {
	tag, err := s.db.Exec(ctx,
		`UPDATE help_requests SET failure_reason = $1, updated_at = now() WHERE id = $2`, reason, id)
	if err != nil {
		return fmt.Errorf("store: setting failure reason: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("%w: id %s", ErrUnknownRequest, id)
	}
	return nil
}

// SetError records the error message for a request that ends status=failed
// (infrastructure/platform error, as opposed to a declined no_fix/no_hint).
func (s *Store) SetError(ctx context.Context, id uuid.UUID, message string) error {
	tag, err := s.db.Exec(ctx,
		`UPDATE help_requests SET error = $1, updated_at = now() WHERE id = $2`, message, id)
	if err != nil {
		return fmt.Errorf("store: setting error: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("%w: id %s", ErrUnknownRequest, id)
	}
	return nil
}

// AppendEvent inserts one events row.
func (s *Store) AppendEvent(ctx context.Context, requestID uuid.UUID, kind string, payload []byte) error {
	if len(payload) == 0 {
		payload = []byte("{}")
	}
	_, err := s.db.Exec(ctx,
		`INSERT INTO events (id, request_id, kind, payload) VALUES ($1, $2, $3, $4)`,
		uuid.New(), requestID, kind, payload,
	)
	if err != nil {
		if isForeignKeyViolation(err) {
			return fmt.Errorf("%w: id %s", ErrUnknownRequest, requestID)
		}
		return fmt.Errorf("store: appending event: %w", err)
	}
	return nil
}

// Event is an events row, as read back for tests/analytics.
type Event struct {
	ID        uuid.UUID
	RequestID uuid.UUID
	Kind      string
	Payload   []byte
	CreatedAt time.Time
}

// ListEvents returns every events row for a request, oldest first.
func (s *Store) ListEvents(ctx context.Context, requestID uuid.UUID) ([]Event, error) {
	rows, err := s.db.Query(ctx, `
		SELECT id, request_id, kind, payload, created_at
		FROM events WHERE request_id = $1 ORDER BY created_at, id`, requestID)
	if err != nil {
		return nil, fmt.Errorf("store: listing events: %w", err)
	}
	defer rows.Close()

	var out []Event
	for rows.Next() {
		var e Event
		if err := rows.Scan(&e.ID, &e.RequestID, &e.Kind, &e.Payload, &e.CreatedAt); err != nil {
			return nil, fmt.Errorf("store: scanning event: %w", err)
		}
		out = append(out, e)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterating events: %w", err)
	}
	return out, nil
}

// LLMCall is one llm_calls row. Cost is a decimal literal (e.g. "0.003400")
// so precision is never lost through a float — it is cast to the numeric
// column with ::numeric.
type LLMCall struct {
	ID                uuid.UUID
	RequestID         uuid.UUID
	Agent             string
	Model             string
	InputTokens       int
	CachedInputTokens int
	OutputTokens      int
	Cost              string
	LatencyMS         int
	Attempt           int
	Prompt            string
	Response          string
}

// InsertLLMCall inserts one llm_calls row.
func (s *Store) InsertLLMCall(ctx context.Context, c LLMCall) error {
	id := c.ID
	if id == uuid.Nil {
		id = uuid.New()
	}
	_, err := s.db.Exec(ctx, `
		INSERT INTO llm_calls (
			id, request_id, agent, model, input_tokens, cached_input_tokens,
			output_tokens, cost, latency_ms, attempt, prompt, response
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8::numeric, $9, $10, $11, $12)`,
		id, c.RequestID, c.Agent, c.Model, c.InputTokens, c.CachedInputTokens,
		c.OutputTokens, c.Cost, c.LatencyMS, c.Attempt, c.Prompt, c.Response,
	)
	if err != nil {
		if isForeignKeyViolation(err) {
			return fmt.Errorf("%w: id %s", ErrUnknownRequest, c.RequestID)
		}
		return fmt.Errorf("store: inserting llm call: %w", err)
	}
	return nil
}

// GetLLMCall fetches one llm_calls row, with cost read back as its exact
// decimal text (never a float).
func (s *Store) GetLLMCall(ctx context.Context, id uuid.UUID) (*LLMCall, error) {
	row := s.db.QueryRow(ctx, `
		SELECT id, request_id, agent, model, input_tokens, cached_input_tokens,
		       output_tokens, cost::text, latency_ms, attempt, prompt, response
		FROM llm_calls WHERE id = $1`, id)

	var c LLMCall
	if err := row.Scan(
		&c.ID, &c.RequestID, &c.Agent, &c.Model, &c.InputTokens, &c.CachedInputTokens,
		&c.OutputTokens, &c.Cost, &c.LatencyMS, &c.Attempt, &c.Prompt, &c.Response,
	); err != nil {
		return nil, fmt.Errorf("store: getting llm call: %w", err)
	}
	return &c, nil
}

// Submission is one snapshotted submission row.
type Submission struct {
	ID                   uuid.UUID
	RequestID            uuid.UUID
	PlatformSubmissionID string
	Code                 string
	Language             string
	TestsPassed          int
	TestsTotal           int
	SubmittedAt          time.Time
	IsBest               bool
}

// SnapshotSubmissions inserts the submissions pulled for one request.
func (s *Store) SnapshotSubmissions(ctx context.Context, requestID uuid.UUID, subs []Submission) error {
	for _, sub := range subs {
		id := sub.ID
		if id == uuid.Nil {
			id = uuid.New()
		}
		_, err := s.db.Exec(ctx, `
			INSERT INTO submissions (
				id, request_id, platform_submission_id, code, language,
				tests_passed, tests_total, submitted_at, is_best
			) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
			id, requestID, sub.PlatformSubmissionID, sub.Code, sub.Language,
			sub.TestsPassed, sub.TestsTotal, sub.SubmittedAt, sub.IsBest,
		)
		if err != nil {
			if isForeignKeyViolation(err) {
				return fmt.Errorf("%w: id %s", ErrUnknownRequest, requestID)
			}
			return fmt.Errorf("store: snapshotting submission: %w", err)
		}
	}
	return nil
}

// ListSubmissions returns every snapshotted submission for a request.
func (s *Store) ListSubmissions(ctx context.Context, requestID uuid.UUID) ([]Submission, error) {
	rows, err := s.db.Query(ctx, `
		SELECT id, request_id, platform_submission_id, code, language,
		       tests_passed, tests_total, submitted_at, is_best
		FROM submissions WHERE request_id = $1 ORDER BY submitted_at`, requestID)
	if err != nil {
		return nil, fmt.Errorf("store: listing submissions: %w", err)
	}
	defer rows.Close()

	var out []Submission
	for rows.Next() {
		var sub Submission
		if err := rows.Scan(
			&sub.ID, &sub.RequestID, &sub.PlatformSubmissionID, &sub.Code, &sub.Language,
			&sub.TestsPassed, &sub.TestsTotal, &sub.SubmittedAt, &sub.IsBest,
		); err != nil {
			return nil, fmt.Errorf("store: scanning submission: %w", err)
		}
		out = append(out, sub)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterating submissions: %w", err)
	}
	return out, nil
}

// GetSubmission fetches one submissions row by id — used by a
// crash-resumed pipeline to reload the best submission it already
// snapshotted and picked before its last checkpoint.
func (s *Store) GetSubmission(ctx context.Context, id uuid.UUID) (*Submission, error) {
	row := s.db.QueryRow(ctx, `
		SELECT id, request_id, platform_submission_id, code, language,
		       tests_passed, tests_total, submitted_at, is_best
		FROM submissions WHERE id = $1`, id)

	var sub Submission
	if err := row.Scan(
		&sub.ID, &sub.RequestID, &sub.PlatformSubmissionID, &sub.Code, &sub.Language,
		&sub.TestsPassed, &sub.TestsTotal, &sub.SubmittedAt, &sub.IsBest,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("store: getting submission: no row with id %s", id)
		}
		return nil, fmt.Errorf("store: getting submission: %w", err)
	}
	return &sub, nil
}

// ShieldRecord is one shield_records row: the audit trail for what the
// shield stripped from a submission before any model saw it. CodeBefore,
// CodeAfter and Diff are all stored deliberately, for audit.
type ShieldRecord struct {
	ID         uuid.UUID
	RequestID  uuid.UUID
	CodeBefore string
	CodeAfter  string
	Diff       string
	Removed    []byte // jsonb: comments, unicode, counts
}

// InsertShieldRecord inserts one shield_records row.
func (s *Store) InsertShieldRecord(ctx context.Context, r ShieldRecord) error {
	id := r.ID
	if id == uuid.Nil {
		id = uuid.New()
	}
	removed := r.Removed
	if len(removed) == 0 {
		removed = []byte("{}")
	}
	_, err := s.db.Exec(ctx, `
		INSERT INTO shield_records (id, request_id, code_before, code_after, diff, removed)
		VALUES ($1, $2, $3, $4, $5, $6)`,
		id, r.RequestID, r.CodeBefore, r.CodeAfter, r.Diff, removed,
	)
	if err != nil {
		if isForeignKeyViolation(err) {
			return fmt.Errorf("%w: id %s", ErrUnknownRequest, r.RequestID)
		}
		return fmt.Errorf("store: inserting shield record: %w", err)
	}
	return nil
}

// GetShieldRecord fetches one shield_records row by id.
func (s *Store) GetShieldRecord(ctx context.Context, id uuid.UUID) (*ShieldRecord, error) {
	row := s.db.QueryRow(ctx, `
		SELECT id, request_id, code_before, code_after, diff, removed
		FROM shield_records WHERE id = $1`, id)

	var r ShieldRecord
	if err := row.Scan(&r.ID, &r.RequestID, &r.CodeBefore, &r.CodeAfter, &r.Diff, &r.Removed); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("store: getting shield record: no row with id %s", id)
		}
		return nil, fmt.Errorf("store: getting shield record: %w", err)
	}
	return &r, nil
}

// GetShieldRecordByRequest fetches the shield_records row for a request —
// used by a crash-resumed pipeline that already shielded the code before
// its last checkpoint, so it never re-shields (and re-inserts) it.
func (s *Store) GetShieldRecordByRequest(ctx context.Context, requestID uuid.UUID) (*ShieldRecord, error) {
	row := s.db.QueryRow(ctx, `
		SELECT id, request_id, code_before, code_after, diff, removed
		FROM shield_records WHERE request_id = $1
		ORDER BY created_at DESC LIMIT 1`, requestID)

	var r ShieldRecord
	if err := row.Scan(&r.ID, &r.RequestID, &r.CodeBefore, &r.CodeAfter, &r.Diff, &r.Removed); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("store: getting shield record: no row for request %s", requestID)
		}
		return nil, fmt.Errorf("store: getting shield record: %w", err)
	}
	return &r, nil
}

// RawMistake is one raw_mistakes row: an unprocessed observation from a
// repair-loop attempt, later folded into a user's mistakes tally by the
// curator (Task 16).
type RawMistake struct {
	ID        uuid.UUID
	RequestID uuid.UUID
	UserID    string
	Text      string
	Processed bool
	CreatedAt time.Time
}

// InsertRawMistake inserts one raw_mistakes row with processed=false.
func (s *Store) InsertRawMistake(ctx context.Context, m RawMistake) error {
	id := m.ID
	if id == uuid.Nil {
		id = uuid.New()
	}
	_, err := s.db.Exec(ctx, `
		INSERT INTO raw_mistakes (id, request_id, user_id, text)
		VALUES ($1, $2, $3, $4)`,
		id, m.RequestID, m.UserID, m.Text,
	)
	if err != nil {
		if isForeignKeyViolation(err) {
			return fmt.Errorf("%w: id %s", ErrUnknownRequest, m.RequestID)
		}
		return fmt.Errorf("store: inserting raw mistake: %w", err)
	}
	return nil
}

// ListRawMistakes returns every raw_mistakes row for a request, oldest first.
func (s *Store) ListRawMistakes(ctx context.Context, requestID uuid.UUID) ([]RawMistake, error) {
	rows, err := s.db.Query(ctx, `
		SELECT id, request_id, user_id, text, processed, created_at
		FROM raw_mistakes WHERE request_id = $1 ORDER BY created_at, id`, requestID)
	if err != nil {
		return nil, fmt.Errorf("store: listing raw mistakes: %w", err)
	}
	defer rows.Close()

	var out []RawMistake
	for rows.Next() {
		var m RawMistake
		if err := rows.Scan(&m.ID, &m.RequestID, &m.UserID, &m.Text, &m.Processed, &m.CreatedAt); err != nil {
			return nil, fmt.Errorf("store: scanning raw mistake: %w", err)
		}
		out = append(out, m)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterating raw mistakes: %w", err)
	}
	return out, nil
}

// ErrUnknownMistake is returned when an operation references a mistakes id
// that has no row.
var ErrUnknownMistake = errors.New("store: unknown mistake")

// ListUnprocessedRawMistakes returns every raw_mistakes row for a user that
// the curator (Task 16) has not yet folded into mistakes, oldest first —
// the batch one curator Run call processes together.
func (s *Store) ListUnprocessedRawMistakes(ctx context.Context, userID string) ([]RawMistake, error) {
	rows, err := s.db.Query(ctx, `
		SELECT id, request_id, user_id, text, processed, created_at
		FROM raw_mistakes WHERE user_id = $1 AND NOT processed ORDER BY created_at, id`, userID)
	if err != nil {
		return nil, fmt.Errorf("store: listing unprocessed raw mistakes: %w", err)
	}
	defer rows.Close()

	var out []RawMistake
	for rows.Next() {
		var m RawMistake
		if err := rows.Scan(&m.ID, &m.RequestID, &m.UserID, &m.Text, &m.Processed, &m.CreatedAt); err != nil {
			return nil, fmt.Errorf("store: scanning unprocessed raw mistake: %w", err)
		}
		out = append(out, m)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterating unprocessed raw mistakes: %w", err)
	}
	return out, nil
}

// MarkRawMistakesProcessed marks every raw_mistakes row in ids as
// processed=true — called once the curator's finish tool ends a user's
// batch, so those rows are never resent on a later sweep.
func (s *Store) MarkRawMistakesProcessed(ctx context.Context, ids []uuid.UUID) error {
	if len(ids) == 0 {
		return nil
	}
	if _, err := s.db.Exec(ctx, `UPDATE raw_mistakes SET processed = TRUE WHERE id = ANY($1)`, ids); err != nil {
		return fmt.Errorf("store: marking raw mistakes processed: %w", err)
	}
	return nil
}

// ListUsersWithUnprocessedMistakes returns every distinct user_id with at
// least one unprocessed raw_mistakes row — the nightly metaloop's worklist.
func (s *Store) ListUsersWithUnprocessedMistakes(ctx context.Context) ([]string, error) {
	rows, err := s.db.Query(ctx, `SELECT DISTINCT user_id FROM raw_mistakes WHERE NOT processed ORDER BY user_id`)
	if err != nil {
		return nil, fmt.Errorf("store: listing users with unprocessed mistakes: %w", err)
	}
	defer rows.Close()

	var out []string
	for rows.Next() {
		var userID string
		if err := rows.Scan(&userID); err != nil {
			return nil, fmt.Errorf("store: scanning user id: %w", err)
		}
		out = append(out, userID)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterating users with unprocessed mistakes: %w", err)
	}
	return out, nil
}

// Mistake is one mistakes row: a curated, per-user, per-habit tally the
// curator (Task 16) folds raw_mistakes into. Top-N by Count desc, LastSeen
// desc feeds the repair agent's prompt (Task 8).
type Mistake struct {
	ID          uuid.UUID
	UserID      string
	Title       string
	Description string
	Count       int
	FirstSeen   time.Time
	LastSeen    time.Time
}

// CreateMistake inserts a new mistakes row with count=1 — the curator's
// create_mistake tool, called for a genuinely new habit.
//
// first_seen/last_seen are set explicitly from clock_timestamp() rather
// than left to the column default (now()): now() is frozen to transaction
// start, so within one multi-statement test transaction every default
// would read identically and the top-N "count desc, last_seen desc"
// ordering (and MergeMistake's bump, below) could never be observed to
// move forward. clock_timestamp() advances on every call, transaction or
// not, matching what "last_seen" needs to mean.
func (s *Store) CreateMistake(ctx context.Context, m Mistake) error {
	id := m.ID
	if id == uuid.Nil {
		id = uuid.New()
	}
	_, err := s.db.Exec(ctx, `
		INSERT INTO mistakes (id, user_id, title, description, first_seen, last_seen)
		VALUES ($1, $2, $3, $4, clock_timestamp(), clock_timestamp())`,
		id, m.UserID, m.Title, m.Description,
	)
	if err != nil {
		return fmt.Errorf("store: creating mistake: %w", err)
	}
	return nil
}

// MergeMistake increments an existing mistakes row's count and bumps
// last_seen to the current time — the curator's merge_into tool, called
// when a raw mistake is judged the same underlying habit as one already on
// file. See CreateMistake for why this uses clock_timestamp(), not now().
func (s *Store) MergeMistake(ctx context.Context, id uuid.UUID) error {
	tag, err := s.db.Exec(ctx, `UPDATE mistakes SET count = count + 1, last_seen = clock_timestamp() WHERE id = $1`, id)
	if err != nil {
		return fmt.Errorf("store: merging mistake: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("%w: id %s", ErrUnknownMistake, id)
	}
	return nil
}

// ListMistakes returns every mistakes row for a user, most recently seen
// first — the curator's "already remembered" context.
func (s *Store) ListMistakes(ctx context.Context, userID string) ([]Mistake, error) {
	rows, err := s.db.Query(ctx, `
		SELECT id, user_id, title, description, count, first_seen, last_seen
		FROM mistakes WHERE user_id = $1 ORDER BY last_seen DESC`, userID)
	if err != nil {
		return nil, fmt.Errorf("store: listing mistakes: %w", err)
	}
	defer rows.Close()

	var out []Mistake
	for rows.Next() {
		var m Mistake
		if err := rows.Scan(&m.ID, &m.UserID, &m.Title, &m.Description, &m.Count, &m.FirstSeen, &m.LastSeen); err != nil {
			return nil, fmt.Errorf("store: scanning mistake: %w", err)
		}
		out = append(out, m)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterating mistakes: %w", err)
	}
	return out, nil
}

// TopMistakes returns a user's mistakes ordered by count desc, then
// last_seen desc, limited to limit rows — what the repair prompt (Task 8)
// consumes as "this student's top-N recurring mistakes".
func (s *Store) TopMistakes(ctx context.Context, userID string, limit int) ([]Mistake, error) {
	rows, err := s.db.Query(ctx, `
		SELECT id, user_id, title, description, count, first_seen, last_seen
		FROM mistakes WHERE user_id = $1
		ORDER BY count DESC, last_seen DESC
		LIMIT $2`, userID, limit)
	if err != nil {
		return nil, fmt.Errorf("store: listing top mistakes: %w", err)
	}
	defer rows.Close()

	var out []Mistake
	for rows.Next() {
		var m Mistake
		if err := rows.Scan(&m.ID, &m.UserID, &m.Title, &m.Description, &m.Count, &m.FirstSeen, &m.LastSeen); err != nil {
			return nil, fmt.Errorf("store: scanning top mistake: %w", err)
		}
		out = append(out, m)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterating top mistakes: %w", err)
	}
	return out, nil
}

// Hint is one hints row. The cache is deliberately cross-user: (ProblemID,
// CodeHash) identifies a defect, not a student, so an approved hint can be
// re-delivered to any request that hashes to the same post-shield code.
type Hint struct {
	ID        uuid.UUID
	RequestID uuid.UUID
	ProblemID string
	CodeHash  string
	Text      string
	Approved  bool
	CreatedAt time.Time
}

// InsertHint inserts one hints row.
func (s *Store) InsertHint(ctx context.Context, h Hint) error {
	id := h.ID
	if id == uuid.Nil {
		id = uuid.New()
	}
	_, err := s.db.Exec(ctx, `
		INSERT INTO hints (id, request_id, problem_id, code_hash, text, approved)
		VALUES ($1, $2, $3, $4, $5, $6)`,
		id, h.RequestID, h.ProblemID, h.CodeHash, h.Text, h.Approved,
	)
	if err != nil {
		if isForeignKeyViolation(err) {
			return fmt.Errorf("%w: id %s", ErrUnknownRequest, h.RequestID)
		}
		return fmt.Errorf("store: inserting hint: %w", err)
	}
	return nil
}

// GetHint fetches one hints row by id.
func (s *Store) GetHint(ctx context.Context, id uuid.UUID) (*Hint, error) {
	row := s.db.QueryRow(ctx, `
		SELECT id, request_id, problem_id, code_hash, text, approved, created_at
		FROM hints WHERE id = $1`, id)

	var h Hint
	if err := row.Scan(&h.ID, &h.RequestID, &h.ProblemID, &h.CodeHash, &h.Text, &h.Approved, &h.CreatedAt); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("store: getting hint: no row with id %s", id)
		}
		return nil, fmt.Errorf("store: getting hint: %w", err)
	}
	return &h, nil
}

// FindApprovedHint returns the approved hint cached for this problem +
// post-shield code hash, or nil if none exists — a miss is not an error.
func (s *Store) FindApprovedHint(ctx context.Context, problemID, codeHash string) (*Hint, error) {
	row := s.db.QueryRow(ctx, `
		SELECT id, request_id, problem_id, code_hash, text, approved, created_at
		FROM hints
		WHERE problem_id = $1 AND code_hash = $2 AND approved
		ORDER BY created_at DESC
		LIMIT 1`, problemID, codeHash)

	var h Hint
	if err := row.Scan(&h.ID, &h.RequestID, &h.ProblemID, &h.CodeHash, &h.Text, &h.Approved, &h.CreatedAt); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("store: finding approved hint: %w", err)
	}
	return &h, nil
}

// CountRequestsSince counts help_requests rows created by a user at or after
// since — the rate-limit query behind the API's daily_requests_per_user cap.
func (s *Store) CountRequestsSince(ctx context.Context, userID string, since time.Time) (int, error) {
	row := s.db.QueryRow(ctx,
		`SELECT count(*) FROM help_requests WHERE user_id = $1 AND created_at >= $2`,
		userID, since,
	)
	var n int
	if err := row.Scan(&n); err != nil {
		return 0, fmt.Errorf("store: counting requests since %s: %w", since, err)
	}
	return n, nil
}

func isUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23505"
}

func isForeignKeyViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23503"
}
