// Package store is the Postgres-backed persistence layer: schema migrations,
// help_requests status transitions, submission snapshots, and the
// append-only events/llm_calls logs.
package store

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/profoundmentalretardation/problem-helper/migrations"
)

// Status is a help_requests.status value.
type Status string

const (
	StatusPending       Status = "pending"
	StatusRunning       Status = "running"
	StatusAlreadySolved Status = "already_solved"
	StatusNoSubmissions Status = "no_submissions"
	StatusDone          Status = "done"
	StatusNoFix         Status = "no_fix"
	StatusNoHint        Status = "no_hint"
	StatusFailed        Status = "failed"
)

// legalTransitions is the status graph from the plan's Technical Details:
// pending -> running -> {terminal...}; running -> pending is the crash
// reclaim path. Any status absent as a key is terminal.
var legalTransitions = map[Status][]Status{
	StatusPending: {StatusRunning},
	StatusRunning: {
		StatusAlreadySolved,
		StatusNoSubmissions,
		StatusDone,
		StatusNoFix,
		StatusNoHint,
		StatusFailed,
		StatusPending,
	},
}

// ErrDuplicateRequest is returned when a help_requests row with the same id
// already exists.
var ErrDuplicateRequest = errors.New("store: help request already exists")

// ErrUnknownRequest is returned when an operation references a request_id
// that has no help_requests row.
var ErrUnknownRequest = errors.New("store: unknown request")

// ErrIllegalTransition is returned when a status transition is not allowed
// by the graph in the plan's Technical Details.
type ErrIllegalTransition struct {
	From, To Status
}

func (e *ErrIllegalTransition) Error() string {
	return fmt.Sprintf("store: illegal status transition from %q to %q", e.From, e.To)
}

// dbtx is satisfied by *pgxpool.Pool, *pgxpool.Conn and pgx.Tx, so Store can
// run either against the pool directly or against a single transaction
// (see store_test.go for the test-isolation rationale).
type dbtx interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

// Store is the persistence layer, bound to either a pool or a transaction.
type Store struct {
	db dbtx
}

// New wraps a connected pool.
func New(pool *pgxpool.Pool) *Store {
	return &Store{db: pool}
}

// WithTx returns a Store bound to tx instead of the original pool/conn —
// used by tests to isolate each test in a rolled-back transaction.
func WithTx(tx pgx.Tx) *Store {
	return &Store{db: tx}
}

// Migrate applies every migrations/*.sql file, in filename order, that has
// not already been recorded in schema_migrations. Safe to call repeatedly.
func Migrate(ctx context.Context, pool *pgxpool.Pool) error {
	if _, err := pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS schema_migrations (
			name        TEXT PRIMARY KEY,
			applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
		)`); err != nil {
		return fmt.Errorf("store: creating schema_migrations: %w", err)
	}

	entries, err := migrations.FS.ReadDir(".")
	if err != nil {
		return fmt.Errorf("store: reading migrations dir: %w", err)
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".sql") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)

	for _, name := range names {
		var applied bool
		if err := pool.QueryRow(ctx,
			`SELECT EXISTS (SELECT 1 FROM schema_migrations WHERE name = $1)`, name,
		).Scan(&applied); err != nil {
			return fmt.Errorf("store: checking migration %s: %w", name, err)
		}
		if applied {
			continue
		}

		sqlBytes, err := migrations.FS.ReadFile(name)
		if err != nil {
			return fmt.Errorf("store: reading migration %s: %w", name, err)
		}

		tx, err := pool.Begin(ctx)
		if err != nil {
			return fmt.Errorf("store: beginning migration tx for %s: %w", name, err)
		}
		if _, err := tx.Exec(ctx, string(sqlBytes)); err != nil {
			_ = tx.Rollback(ctx)
			return fmt.Errorf("store: applying migration %s: %w", name, err)
		}
		if _, err := tx.Exec(ctx,
			`INSERT INTO schema_migrations (name) VALUES ($1)`, name,
		); err != nil {
			_ = tx.Rollback(ctx)
			return fmt.Errorf("store: recording migration %s: %w", name, err)
		}
		if err := tx.Commit(ctx); err != nil {
			return fmt.Errorf("store: committing migration %s: %w", name, err)
		}
	}
	return nil
}

// HelpRequestInput creates a help_requests row; the caller supplies ID
// (generated by the API layer) since request_id is returned synchronously
// from POST /help before the worker ever runs.
type HelpRequestInput struct {
	ID                uuid.UUID
	UserID            string
	ProblemID         string
	Platform          string
	NSubmissionsTaken int
}

// HelpRequest is a help_requests row.
type HelpRequest struct {
	ID                uuid.UUID
	UserID            string
	ProblemID         string
	Platform          string
	NSubmissionsTaken int
	Status            Status
	FailureReason     *string
	BestSubmissionID  *uuid.UUID
	HintID            *uuid.UUID
	Useless           bool
	Error             *string
	ClaimedBy         *string
	HeartbeatAt       *time.Time
	ResumeStep        *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// CreateHelpRequest inserts a new help_requests row with status=pending.
func (s *Store) CreateHelpRequest(ctx context.Context, in HelpRequestInput) error {
	_, err := s.db.Exec(ctx, `
		INSERT INTO help_requests (id, user_id, problem_id, platform, n_submissions_taken, status)
		VALUES ($1, $2, $3, $4, $5, $6)`,
		in.ID, in.UserID, in.ProblemID, in.Platform, in.NSubmissionsTaken, StatusPending,
	)
	if err != nil {
		if isUniqueViolation(err) {
			return fmt.Errorf("%w: id %s", ErrDuplicateRequest, in.ID)
		}
		return fmt.Errorf("store: creating help request: %w", err)
	}
	return nil
}

// GetHelpRequest fetches a help_requests row by id.
func (s *Store) GetHelpRequest(ctx context.Context, id uuid.UUID) (*HelpRequest, error) {
	row := s.db.QueryRow(ctx, `
		SELECT id, user_id, problem_id, platform, n_submissions_taken, status,
		       failure_reason, best_submission_id, hint_id, useless, error,
		       claimed_by, heartbeat_at, resume_step, created_at, updated_at
		FROM help_requests WHERE id = $1`, id)

	var hr HelpRequest
	var status string
	if err := row.Scan(
		&hr.ID, &hr.UserID, &hr.ProblemID, &hr.Platform, &hr.NSubmissionsTaken, &status,
		&hr.FailureReason, &hr.BestSubmissionID, &hr.HintID, &hr.Useless, &hr.Error,
		&hr.ClaimedBy, &hr.HeartbeatAt, &hr.ResumeStep, &hr.CreatedAt, &hr.UpdatedAt,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("%w: id %s", ErrUnknownRequest, id)
		}
		return nil, fmt.Errorf("store: getting help request: %w", err)
	}
	hr.Status = Status(status)
	return &hr, nil
}

// TransitionStatus moves a help_requests row to a new status, validating the
// transition against the graph in the plan's Technical Details. Illegal
// transitions (including any transition out of a terminal status) return
// *ErrIllegalTransition and do not modify the row.
func (s *Store) TransitionStatus(ctx context.Context, id uuid.UUID, to Status) error {
	row := s.db.QueryRow(ctx, `SELECT status FROM help_requests WHERE id = $1 FOR UPDATE`, id)
	var current string
	if err := row.Scan(&current); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return fmt.Errorf("%w: id %s", ErrUnknownRequest, id)
		}
		return fmt.Errorf("store: reading status for transition: %w", err)
	}
	from := Status(current)

	if !isLegalTransition(from, to) {
		return &ErrIllegalTransition{From: from, To: to}
	}

	if _, err := s.db.Exec(ctx,
		`UPDATE help_requests SET status = $1, updated_at = now() WHERE id = $2`, to, id,
	); err != nil {
		return fmt.Errorf("store: updating status: %w", err)
	}
	return nil
}

func isLegalTransition(from, to Status) bool {
	for _, allowed := range legalTransitions[from] {
		if allowed == to {
			return true
		}
	}
	return false
}

// AppendEvent inserts one events row.
func (s *Store) AppendEvent(ctx context.Context, requestID uuid.UUID, kind string, payload []byte) error {
	if len(payload) == 0 {
		payload = []byte("{}")
	}
	_, err := s.db.Exec(ctx,
		`INSERT INTO events (id, request_id, kind, payload) VALUES ($1, $2, $3, $4)`,
		uuid.New(), requestID, kind, payload,
	)
	if err != nil {
		if isForeignKeyViolation(err) {
			return fmt.Errorf("%w: id %s", ErrUnknownRequest, requestID)
		}
		return fmt.Errorf("store: appending event: %w", err)
	}
	return nil
}

// Event is an events row, as read back for tests/analytics.
type Event struct {
	ID        uuid.UUID
	RequestID uuid.UUID
	Kind      string
	Payload   []byte
	CreatedAt time.Time
}

// ListEvents returns every events row for a request, oldest first.
func (s *Store) ListEvents(ctx context.Context, requestID uuid.UUID) ([]Event, error) {
	rows, err := s.db.Query(ctx, `
		SELECT id, request_id, kind, payload, created_at
		FROM events WHERE request_id = $1 ORDER BY created_at, id`, requestID)
	if err != nil {
		return nil, fmt.Errorf("store: listing events: %w", err)
	}
	defer rows.Close()

	var out []Event
	for rows.Next() {
		var e Event
		if err := rows.Scan(&e.ID, &e.RequestID, &e.Kind, &e.Payload, &e.CreatedAt); err != nil {
			return nil, fmt.Errorf("store: scanning event: %w", err)
		}
		out = append(out, e)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterating events: %w", err)
	}
	return out, nil
}

// LLMCall is one llm_calls row. Cost is a decimal literal (e.g. "0.003400")
// so precision is never lost through a float — it is cast to the numeric
// column with ::numeric.
type LLMCall struct {
	ID                uuid.UUID
	RequestID         uuid.UUID
	Agent             string
	Model             string
	InputTokens       int
	CachedInputTokens int
	OutputTokens      int
	Cost              string
	LatencyMS         int
	Attempt           int
	Prompt            string
	Response          string
}

// InsertLLMCall inserts one llm_calls row.
func (s *Store) InsertLLMCall(ctx context.Context, c LLMCall) error {
	id := c.ID
	if id == uuid.Nil {
		id = uuid.New()
	}
	_, err := s.db.Exec(ctx, `
		INSERT INTO llm_calls (
			id, request_id, agent, model, input_tokens, cached_input_tokens,
			output_tokens, cost, latency_ms, attempt, prompt, response
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8::numeric, $9, $10, $11, $12)`,
		id, c.RequestID, c.Agent, c.Model, c.InputTokens, c.CachedInputTokens,
		c.OutputTokens, c.Cost, c.LatencyMS, c.Attempt, c.Prompt, c.Response,
	)
	if err != nil {
		if isForeignKeyViolation(err) {
			return fmt.Errorf("%w: id %s", ErrUnknownRequest, c.RequestID)
		}
		return fmt.Errorf("store: inserting llm call: %w", err)
	}
	return nil
}

// GetLLMCall fetches one llm_calls row, with cost read back as its exact
// decimal text (never a float).
func (s *Store) GetLLMCall(ctx context.Context, id uuid.UUID) (*LLMCall, error) {
	row := s.db.QueryRow(ctx, `
		SELECT id, request_id, agent, model, input_tokens, cached_input_tokens,
		       output_tokens, cost::text, latency_ms, attempt, prompt, response
		FROM llm_calls WHERE id = $1`, id)

	var c LLMCall
	if err := row.Scan(
		&c.ID, &c.RequestID, &c.Agent, &c.Model, &c.InputTokens, &c.CachedInputTokens,
		&c.OutputTokens, &c.Cost, &c.LatencyMS, &c.Attempt, &c.Prompt, &c.Response,
	); err != nil {
		return nil, fmt.Errorf("store: getting llm call: %w", err)
	}
	return &c, nil
}

// Submission is one snapshotted submission row.
type Submission struct {
	ID                   uuid.UUID
	RequestID            uuid.UUID
	PlatformSubmissionID string
	Code                 string
	Language             string
	TestsPassed          int
	TestsTotal           int
	SubmittedAt          time.Time
	IsBest               bool
}

// SnapshotSubmissions inserts the submissions pulled for one request.
func (s *Store) SnapshotSubmissions(ctx context.Context, requestID uuid.UUID, subs []Submission) error {
	for _, sub := range subs {
		id := sub.ID
		if id == uuid.Nil {
			id = uuid.New()
		}
		_, err := s.db.Exec(ctx, `
			INSERT INTO submissions (
				id, request_id, platform_submission_id, code, language,
				tests_passed, tests_total, submitted_at, is_best
			) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
			id, requestID, sub.PlatformSubmissionID, sub.Code, sub.Language,
			sub.TestsPassed, sub.TestsTotal, sub.SubmittedAt, sub.IsBest,
		)
		if err != nil {
			if isForeignKeyViolation(err) {
				return fmt.Errorf("%w: id %s", ErrUnknownRequest, requestID)
			}
			return fmt.Errorf("store: snapshotting submission: %w", err)
		}
	}
	return nil
}

// ListSubmissions returns every snapshotted submission for a request.
func (s *Store) ListSubmissions(ctx context.Context, requestID uuid.UUID) ([]Submission, error) {
	rows, err := s.db.Query(ctx, `
		SELECT id, request_id, platform_submission_id, code, language,
		       tests_passed, tests_total, submitted_at, is_best
		FROM submissions WHERE request_id = $1 ORDER BY submitted_at`, requestID)
	if err != nil {
		return nil, fmt.Errorf("store: listing submissions: %w", err)
	}
	defer rows.Close()

	var out []Submission
	for rows.Next() {
		var sub Submission
		if err := rows.Scan(
			&sub.ID, &sub.RequestID, &sub.PlatformSubmissionID, &sub.Code, &sub.Language,
			&sub.TestsPassed, &sub.TestsTotal, &sub.SubmittedAt, &sub.IsBest,
		); err != nil {
			return nil, fmt.Errorf("store: scanning submission: %w", err)
		}
		out = append(out, sub)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterating submissions: %w", err)
	}
	return out, nil
}

// ShieldRecord is one shield_records row: the audit trail for what the
// shield stripped from a submission before any model saw it. CodeBefore,
// CodeAfter and Diff are all stored deliberately, for audit.
type ShieldRecord struct {
	ID         uuid.UUID
	RequestID  uuid.UUID
	CodeBefore string
	CodeAfter  string
	Diff       string
	Removed    []byte // jsonb: comments, unicode, counts
}

// InsertShieldRecord inserts one shield_records row.
func (s *Store) InsertShieldRecord(ctx context.Context, r ShieldRecord) error {
	id := r.ID
	if id == uuid.Nil {
		id = uuid.New()
	}
	removed := r.Removed
	if len(removed) == 0 {
		removed = []byte("{}")
	}
	_, err := s.db.Exec(ctx, `
		INSERT INTO shield_records (id, request_id, code_before, code_after, diff, removed)
		VALUES ($1, $2, $3, $4, $5, $6)`,
		id, r.RequestID, r.CodeBefore, r.CodeAfter, r.Diff, removed,
	)
	if err != nil {
		if isForeignKeyViolation(err) {
			return fmt.Errorf("%w: id %s", ErrUnknownRequest, r.RequestID)
		}
		return fmt.Errorf("store: inserting shield record: %w", err)
	}
	return nil
}

// GetShieldRecord fetches one shield_records row by id.
func (s *Store) GetShieldRecord(ctx context.Context, id uuid.UUID) (*ShieldRecord, error) {
	row := s.db.QueryRow(ctx, `
		SELECT id, request_id, code_before, code_after, diff, removed
		FROM shield_records WHERE id = $1`, id)

	var r ShieldRecord
	if err := row.Scan(&r.ID, &r.RequestID, &r.CodeBefore, &r.CodeAfter, &r.Diff, &r.Removed); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("store: getting shield record: no row with id %s", id)
		}
		return nil, fmt.Errorf("store: getting shield record: %w", err)
	}
	return &r, nil
}

func isUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23505"
}

func isForeignKeyViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23503"
}
