#!/usr/bin/env python3
"""Capture the slice-B trace against a live model. Writes traces/b_curator.md.

Run from the repo root:  .venv/bin/python scratch/trace_b.py
Needs LLM_BASE_URL and LLM_API_KEY. Starts from empty stores so the trace shows the whole
path: an empty store, one run, and the fact coming back on its cue in the next one.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd()))

from memory import db, events                                  # noqa: E402
from memory.docs import Session, render_facts, retrieve_facts   # noqa: E402

for p in (db.facts_path(), db.events_path(), db.db_path()):
    p.unlink(missing_ok=True)

import importlib.util                                          # noqa: E402

spec = importlib.util.spec_from_file_location("nb4", "scratch/nb4.py")
nb4 = importlib.util.module_from_spec(spec)
sys.modules["nb4"] = nb4
spec.loader.exec_module(nb4)          # runs the offline tests too; they use their own sandbox

# The tests above restored the real stores, but they also emptied them again. Start clean.
for p in (db.facts_path(), db.events_path(), db.db_path()):
    p.unlink(missing_ok=True)

out = ["# Trace — the curator (slice B)",
       "",
       "Live model, empty stores at the start. Generated by `scratch/trace_b.py`; every block",
       "below is copied out of the run, not written by hand.",
       ""]


def block(title, body, lang=""):
    out.extend([f"## {title}", "", f"```{lang}", body.rstrip(), "```", ""])


A, B = Session("u42"), Session("u77")

# ---------------------------------------------------------------- 1. the noisy run
r_noise = nb4.run_curator(nb4.NOISE_ENVELOPE, confirm=lambda q: False)
block("1. A run with nothing in it — the hand-off the executor passes",
      json.dumps({"status": nb4.NOISE_ENVELOPE["status"],
                  "result": {k: v for k, v in nb4.NOISE_ENVELOPE["result"].items()
                             if k in ("run_id", "problem_id", "mistake_tag", "student_said")},
                  "needs_approval": nb4.NOISE_ENVELOPE["needs_approval"]}, indent=2), "json")
block("...and what the curator did with it",
      f"status : {r_noise['status']}\n"
      f"calls  : {r_noise['calls']}\n"
      f"reason : {r_noise.get('reason', '')}\n"
      f"saved  : {len(r_noise['saved'])}")

# ---------------------------------------------------------------- 2. the real run
r_real = nb4.run_curator(nb4.ENVELOPE, confirm=lambda q: False)
said = nb4.ENVELOPE["result"]["student_said"]
block("2. A run with a real preference in it", f'the student, verbatim:\n"{said}"')
lines = [f"status : {r_real['status']}", f"calls  : {r_real['calls']}",
         f"reason : {r_real.get('reason', '')}", ""]
for f in r_real["saved"]:
    lines += [f"saved  [{f['scope']}] {f['text']}", f"       cue: {f['cue']}"]
for p in r_real["proposed"]:
    lines.append(f"proposed rule (applied={p['applied']}): {p['line']}")
block("...and what it decided to keep", "\n".join(lines))

# ---------------------------------------------------------------- 3. the trail
run_id = nb4.ENVELOPE["result"]["run_id"]
trail = [f'{e["seq"]:>3}  {e["kind"]:<14} {json.dumps(e["payload"], ensure_ascii=False)[:150]}'
         for e in events.read_events(run_id=run_id)]
block("3. The trail both agents left, one run_id", "\n".join(trail))
block("...the hand-off rows",
      "\n".join(f'{h["from_agent"]} -> {h["to_agent"]}  status={h["status"]}  '
                f'needs_approval={h["needs_approval"]}' for h in events.handoffs_for(run_id)))
block("...and the chain over the whole log", json.dumps(events.verify_chain()), "json")

# ---------------------------------------------------------------- 4. the next run
query = "he sent me python again for an easy one and the input reading is off"
hits = retrieve_facts(A, query)
block("4. The next run, days later — the same student asks something else",
      f"request: {query}\n\nwhat the retrieve tool pulled back, on the cue the curator wrote:\n\n"
      + (render_facts(hits) or "(nothing)"))

other = retrieve_facts(B, query)
block("...the identical request, from a different student",
      f"request: {query}\nretrieved: {other if other else '[] — nothing. u42s facts are not in u77s scope.'}")

Path("traces").mkdir(exist_ok=True)
Path("traces/b_curator.md").write_text("\n".join(out))
print("wrote traces/b_curator.md")
